### ISSUE TITLE
doorklikken bij coderingen

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#11]
Grafieken met coderingen kan je nu wel doorklikken, maar geeft verkeerd aantal resultaten. Tabellen geeft hij een fout dat je niet kan doorklikken. Op amcat kan je wel een article list opvragen van coderingen (maar zie https://github.com/amcat/amcat/issues/696)

**Comment by CJStuart** [comment]
Fixed in https://github.com/amcat/amcat/commit/ed16ee134fa4f7fccba8aacaa05540327ec3596f, but still needs some testing.

Also some unit tests need to be updated accordingly.

**Comment by CJStuart** [comment]
On the dashboard side, this should work.

@nruigrok could you verify this?

(There's still an open issue regarding erroneous results in aggregations with codebooks: amcat/amcat#703. This might lead the number of articles in the table not matching the number shown in the graph. This is a bug in the graph, the table number is correct.)

**Comment by nruigrok** [comment]
This is not working yet. Dashboard states: Viewing articles / codings not yet supported in coding aggregations.

**Comment by CJStuart** [comment]
That shouldn't happen anymore with the latest version of amcat-query-js. I just ran a bower update for the dashboard to update it, that should resolve this.

**Comment by CJStuart** [comment]
I believe the last of these issues was fixed in amcat/amcat-query-js@879f0913914c2966a229630eb9700907fced620c
