### ISSUE TITLE
(recent) article list

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#13]
Amcat query Summary allows you to create a list of articles (also without aggregations). It would be nice to have this as a dashboard output option with a nice layout, e.g. like the lexis nexis news desk:

![image](https://user-images.githubusercontent.com/1736240/45213578-3a702000-b298-11e8-81e5-30755462cb12.png)

**Comment by CJStuart** [comment]
This was implemented in 6b6af7cf8b498cf5f28fb84c051f31572704e185 and https://github.com/amcat/amcat/commit/bf87b453b83c8713763599781f259c677e3bbefe. I also made some changes to the style (#14).

**Comment by CJStuart** [comment]
By the way, it is currently impossible to show just the titles in the summary. If the number of fragments is set to 0 it will return the full text instead.

Perhaps a special case should be added to the summary for when number of fragments is 0?

**Comment by CJStuart** [comment]
has been fixed
