### ISSUE TITLE
beautify the dashboard

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#14]
The dashboard can be made more beautiful with some simple changes such as:

- making the bootstrap panels more minimalistic
- Hiding the icons / actions or collapsing them to a menu button
- adding gradients to highcharts

For inspiration, below is a screenshot of the newsdesk

![image](https://user-images.githubusercontent.com/1736240/45213651-70ad9f80-b298-11e8-8fff-43fe98b0a930.png)

**Comment by nruigrok** [comment]
Bij de themes is het mooi dat je nu de y-as ook kunt instellen met kleurtjes. Wordt BZK heel blij van.
Alleen lijkt het erop dat je maar een y-as doet, niet ook de tweede? Als ik die aanklik krijg ik wel een dikkere lijn maar met zwarte kleur. Zie hieronder. Graag de opties ook voor de tweede y-as
![screenshot from 2019-01-31 21-45-45](https://user-images.githubusercontent.com/6438205/52084195-c7967700-25a1-11e9-9348-650b262368b8.png)

**Comment by CJStuart** [comment]
Volgens mij is het al mogelijk om een andere kleur in te stellen voor de tweede Y as, door de tweede kleur in het schema te veranderen.

**Comment by CJStuart** [comment]
Er is altijd verbetering mogelijk op dit punt, maar ik sluit de issue, aangezien het dashboard er al redelijk goed uitziet.
