### ISSUE TITLE
No output when using coded articles

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#18]
Wat ik ook probeer voor grafiek/tabel te maken met gecodeerde data, de figuur blijft leeg. Zie hieronder:

![image](https://user-images.githubusercontent.com/6438205/48127255-8d0f8d80-e283-11e8-97a6-3aef9de901c5.png)

**Comment by CJStuart** [comment]
An empty filter on 'Onderwerp' was set. Perhaps the form should throw an error on that (or just ignore it) . This one works:

http://bzk.nieuwsmonitor.org/projects/1/query/?query=2&jobs=2146,2149,2143,2151#codingaggregation

**Comment by nruigrok** [comment]
I tried to do that but the figure stays empty, also with 100 coded articles in which for sure something must occur...

![image](https://user-images.githubusercontent.com/6438205/48127998-710ceb80-e285-11e8-96dd-0ff2b70daa89.png)

**Comment by CJStuart** [comment]
This was fixed, right?

**Comment by nruigrok** [comment]
Yes!


Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org
