### ISSUE TITLE
Theme page doesn't show the names of themes

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#19]
Op de pagina waar de Themes staan zie je alleen de eerste in kleurtjes. Daaronder staan alleen maar buttons met EDIT en DELETE zonder de naam van de themes. Het zou handig zijn als in ieder geval de naam van de thema's ook zichtbaar is zodat je daar op kan klikken en zien hoe het eruit ziet.

**Comment by CJStuart** [comment]
Volgens mij wordt de naam van een thema wel getoond, als titel van het voorbeeld.
