### ISSUE TITLE
global filters in dashboard

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#2]
This is not an urgent feature, but nice to have. Add global filters for some predefined fields (especially date and text) at the top of the dashboard, that would be added to all loaded queries.

**Comment by nruigrok** [comment]
@CJStuart  Het lijkt mij geweldig als je hiernaar zou willen kijken!

**Comment by vanatteveldt** [comment]
Hey @CJStuart ,

Fijn dat er nu een implementatie hiervan in het dashboard zit! In de huidige vorm lijkt hij echter niet te werken, en in ieder geval is het niet een heel logische manier voor de gebruiker.

Wat ik voor me zie is een zoekbalk bovenin het scherm van een dashboard met daarin een vrij zoekveld en een knop voor een datum popup. Als je dan iets intikt dan worden automatisch alle grafieken in dat dashboard gefilterd op de zoekterm en/of datum en ververst.

Zie bv hoe Coosto het doet:

![image](https://user-images.githubusercontent.com/1736240/42527075-f3ac5b64-8477-11e8-9bdc-4410db686b60.png)

Lijkt je dat haalbaar?
