### ISSUE TITLE
After filter individual articles not shown

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#26]
Wanneer je in het dashboard een algemene filter doet dan kun je vervolgens niet meer op de figuren klikken om de artikelen die er achter liggen te bekijken. Hij blijft hangen. Zie 
![screenshot from 2019-01-31 21-10-38](https://user-images.githubusercontent.com/6438205/52082346-d62e5f80-259c-11e9-8c67-811e9493d92a.png)

**Comment by CJStuart** [comment]
Volgens mij werkt dit wel, maar het kan soms even duren voordat alle gefilterde resultaten zijn geladen.
