### ISSUE TITLE
Customization / i18n

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#3]
For external users it is attractive to offer some minor customization of query result (especially graph) appearance, such as line colour, labels, etc. For example, make the secondary axis red instead of black, and have the label read "Gemiddelde" instead of "Average".

The concrete use case is a separate server, so maybe we can just add a custom-settings.js file somewhere or something like that?

**Comment by nruigrok** [comment]
Specific customization: Now it says series 1 and series 2 for example under a graph or table where it should be giving the actual analysis, like "aantal artikelen" of "teneur van het nieuws" (in dutch...)

Also the tone of the articles, de teneur, should be given in red dots instead of bleu as it is now

**Comment by nruigrok** [comment]
In addition it would be nice if in the graphs on the Dashboard only the labels can be shown in the graph instead of the whole search term as is the case now. So for example if you use wiv#(wet inlichitingen*~5 OR wiv OR sleepwet) that only wiv is mentioned.

**Comment by vanatteveldt** [comment]
what works:
- primary / secondary axis can be changed
- graph colors can be changed

what can be improved:
- change title in dashboard edit
- legend "Number of articles", --> bv "aantal artikelen"
- legenda optioneel weglaten (#6)
- afronden getallen in hover text

**Comment by CJStuart** [comment]
These were all added:

- change title in dashboard edit
- legend "Number of articles", --> bv "aantal artikelen"
- legenda optioneel weglaten (#6)
- afronden getallen in hover text

Are there any other things that should be customizable?
