### ISSUE TITLE
change server/token

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#4]
You can log in with a server when creating a new dashboard, but it seems impossible to change the server/token without the console (easiest solution is simply dropdb and start over). I guess saved queries are probably useless on a new server, but maybe a button to reset settings would be nice. Having different servers for different dashboards (or even queries!) would be even nicer, but not sure if it's worth the bother.

**Comment by CJStuart** [comment]
- [x]  done
