### ISSUE TITLE
Link to original articles

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#5]
Het zou fijn zijn als we vanuit het Dashboard ook kunnen doorklikken naar de originele artikelen, net zoals in het query scherm.

**Comment by CJStuart** [comment]
Is het dan ook de bedoeling dat er bij het klikken op een grafiek een tabel met de betreffende artikelen opent?

**Comment by nruigrok** [comment]
Ja zo'n pop-up zoals bij het query scherm zou fijn zijn!

gr,
Nel



Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org
