### ISSUE TITLE
Waardes x-as en y-as weglaten na customization

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#6]
In het DAshboard kun je nu de teksten op de eeste en tweede y-as zelf weergeven, zodat je geen legenda meer nodig hebt. Dat is heel mooi. Als we dat doen, dan zou het wel fijn zijn als de weergave onderaan de grafiek, waar nu de legenda staat weg gaat. Nu staat het er dubbel.

Ook zou het heel fijn zijn als de beschrijving van de y-as wordt weergegeven in de kleur van de lijn die het representeert. In dit geval dus aantal artikelen lichtblauw en teneur zwart (en deze kleuren moeten dan flexibel zijn al naar gelang het theme dat je selecteert).

Ook als je over de figuur heen scrollt zou het mooi zijn als je de teksten niet meer in het engels ziet maar in de aangepaste vorm van de beide y-assen.  zie bijlage. 

![screenshot from 2018-07-19 07-45-35](https://user-images.githubusercontent.com/6438205/42923870-fc394cf4-8b27-11e8-8a24-31351371d78c.png)

**Comment by vanatteveldt** [comment]
(opgenomenin 3)
